apiVersion: bindplane.observiq.com/v1beta
kind: Receiver
metadata:
  name: macos
spec:
  plugin:
    name: macos
  parameters:
  - name: name
    value: macOS
  - name: start_at
    value: end
  - name: enable_system_log
    value: true
  - name: enable_install_log
    value: true
---
# i have a script that appends to this file
apiVersion: bindplane.observiq.com/v1beta
kind: Receiver
metadata:
  name: tmpfile
spec:
  plugin:
    name: json
  parameters:
  - name: file_log_path
    value: ["/tmp/file.log"]
  - name: multiline_line_start_pattern
    value: ""
  - name: pod_name
    value: ""
  - name: start_at
    value: end
---
apiVersion: bindplane.observiq.com/v1beta
kind: Exporter
metadata:
  name: bindplane-development
spec:
  plugin:
    name: cabin_output
  parameters:
  - name: endpoint
    value: https://nozzle.bindplane.bluemedora.com
  - name: secret_key
    value: e3655ee8-32c4-4750-a8f9-7bcaaa3a50ce
  - name: timeout
    value: 10s
---
apiVersion: bindplane.observiq.com/v1beta
kind: Pipeline
metadata:
  name: local macos pipeline
  labels:
    app: cabin
spec:
  pipeline:
    receivers:
    - macos
    - tmpfile
    processors:
    exporters:
    - bindplane-development
  selector:
    matchLabels:
      "bindplane/agent-os": darwin
