apiVersion: bindplane.observiq.com/v1
kind: DestinationType
metadata:
  name: logging
  displayName: Logging
  icon: /icons/destinations/logging.svg
spec:
  parameters:
    - name: log_level
      label: Log Level
      description: The log level
      type: enum
      validValues:
        - debug
        - info
        - warn
        - error
      default: info
  logs:
    exporters: |
      - logging:
          logLevel: {{ .log_level }}
  metrics:
    exporters: |
      - logging:
          logLevel: {{ .log_level }}
  traces:
    exporters: |
      - logging:
          logLevel: {{ .log_level }}
