version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    commit-message:
      prefix: "deps"
      include: "scope"

  - package-ecosystem: "gomod"
    directory: "/internal/tools"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "tooling"
    commit-message:
      prefix: "deps"
      include: "scope"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    commit-message:
      prefix: "deps"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "continuous integration"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "npm"
    directory: "ui/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "ui"
    commit-message:
      prefix: "deps"
      include: "scope"
