apiVersion: bindplane.observiq.com/v1
kind: Configuration
metadata:
  name: file-extract-duration
spec:
  contentType: text/yaml
  sources:
  # name is optional and this will become MacOS_1 if none is specified or MacOS_name if a name is specified
  - type: file
    parameters:
      - name: file_path
        value:
          - /var/log/http.log
      - name: exclude_file_path
        value: []
      - name: log_type
        value: file
      - name: parse_format
        value: json
      - name: regex_pattern
        value: ""
      - name: multiline_line_start_pattern
        value: ""
      - name: encoding
        value: utf-8
      - name: start_at
        value: end
    processors:
      - type: extract_metric
        parameters:
          - name: match
            value: body.duration != nil
          - name: path
            value: body.duration
          - name: metric_name
            value: http.request.duration
          - name: metric_units
            value: 'ms'
          - name: attributes
            value:
              status_code: body.status
          - name: interval
            value: 60
        disabled: false
  destinations:
  - name: googlecloud
  selector:
    matchLabels:
      "configuration": file-extract-duration
