apiVersion: bindplane.observiq.com/v1
kind: Configuration
metadata:
  name: macos
  labels:
    platform: macos
    app: cabin
spec:
  contentType: text/yaml
  sources:
  # name is optional and this will become MacOS_1 if none is specified or MacOS_name if a name is specified
  - type: MacOS
    parameters:
      # using default parameter values for anything missing
      - name: enable_system_log
        value: false
  - type: MacOS
    parameters:
      # using default parameter values for anything missing
      - name: enable_system_log
        value: true
  destinations:
  - type: googlecloud
    disabled: true
  - name: cabin-production-logs
  selector:
    matchLabels:
      "configuration": macos
