apiVersion: bindplane.observiq.com/v1beta
kind: Source
metadata:
  # Shouldn't be an array
  name: [bar]
  description: bar is my old macbook with a touchbar
spec:
  type: MacOS
  parameters:
    # using default parameter values for anything missing
    - name: enable_system_log
      value: false
