apiVersion: bindplane.observiq.com/v1
kind: SourceType
metadata:
  name: host
  displayName: Host
  icon: /icons/sources/host.svg
  description: Collect metrics from the collector's host.
spec:
  version: 0.0.1
  supported_platforms:
    - macos
    - linux
    - windows
  parameters:
    - name: collection_interval
      label: Collection Interval
      description: How often (seconds) to scrape for metrics.
      type: int
      default: 60
      advancedConfig: true

    # Load Metrics
    - name: enable_load
      label: Load Metrics
      description: Enable to collect load metrics. Compatible with all platforms.
      type: bool
      default: true

    - name: load_metric_filtering
      type: enums
      options:
        trackUnchecked: true
      validValues:
        - system.cpu.load_average.15m
        - system.cpu.load_average.1m
        - system.cpu.load_average.5m
      default: []
      relevantIf:
        - name: enable_load
          operator: equals
          value: true
      advancedConfig: true

    # Filesystem Metrics
    - name: enable_filesystem
      label: Filesystem Metrics
      description: Enable to collect filesystem metrics. Compatible with all platforms.
      type: bool
      default: true

    - name: filesystem_metric_filtering
      type: enums
      options:
        trackUnchecked: true
      validValues:
        - system.filesystem.inodes.usage
        - system.filesystem.usage
        - system.filesystem.utilization
      default: []
      relevantIf:
        - name: enable_filesystem
          operator: equals
          value: true
      advancedConfig: true

    # Memory Metrics
    - name: enable_memory
      label: Memory Metrics
      description: Enable to collect memory metrics. Compatible with all platforms.
      type: bool
      default: true

    - name: memory_metrics_filtering
      type: enums
      options:
        trackUnchecked: true
      validValues:
        - system.memory.usage
        - system.memory.utilization
      default: []
      relevantIf:
        - name: enable_memory
          operator: equals
          value: true
      advancedConfig: true

    # Network Metrics
    - name: enable_network
      label: Network Metrics
      description: Enable to collect network metrics. Compatible with all platforms.
      type: bool
      default: true

    - name: network_metrics_filtering
      type: enums
      options:
        trackUnchecked: true
      validValues:
        - system.network.connections
        - system.network.conntrack.count
        - system.network.conntrack.max
        - system.network.dropped
        - system.network.errors
        - system.network.io
        - system.network.packets
      default: []
      relevantIf:
        - name: enable_network
          operator: equals
          value: true
      advancedConfig: true

    # Paging Metrics
    - name: enable_paging
      label: Paging Metrics
      description: Enable to collect paging metrics. Compatible with all platforms.
      type: bool
      default: true

    - name: paging_metrics_filtering
      type: enums
      options:
        trackUnchecked: true
      validValues:
        - system.paging.faults
        - system.paging.operations
        - system.paging.operations.page_in
        - system.paging.operations.page_out
        - system.paging.usage
        - system.paging.utilization
      default: []
      relevantIf:
        - name: enable_paging
          operator: equals
          value: true
      advancedConfig: true

    # CPU Metrics
    - name: enable_cpu
      label: CPU Metrics
      description: Enable to collect CPU metrics. Compatible with Linux and Windows.
      type: bool
      default: false

    - name: cpu_metrics_filtering
      type: enums
      options:
        trackUnchecked: true
      validValues:
        - system.cpu.time
        - system.cpu.utilization
      default: []
      relevantIf:
        - name: enable_cpu
          operator: equals
          value: true
      advancedConfig: true

    # Disk Metrics
    - name: enable_disk
      label: Disk Metrics
      description: Enable to collect disk metrics. Compatible with Linux and Windows.
      type: bool
      default: false

    - name: disk_metrics_filtering
      type: enums
      options:
        trackUnchecked: true
      validValues:
        - system.disk.io
        - system.disk.io_time
        - system.disk.merged
        - system.disk.operation_time
        - system.disk.operations
        - system.disk.pending_operations
        - system.disk.weighted_io_time
      default: []
      relevantIf:
        - name: enable_disk
          operator: equals
          value: true
      advancedConfig: true

    # Processes Metrics
    - name: enable_processes
      label: Processes Metrics
      description: Enable to collect process count metrics. Compatible with Linux only.
      type: bool
      default: false

    - name: processes_metrics_filtering
      type: enums
      options:
        trackUnchecked: true
      validValues:
        - system.processes.count
        - system.processes.created
      default: []
      relevantIf:
        - name: enable_processes
          operator: equals
          value: true

    # Process metrics w/ filtering
    - name: enable_process
      label: Process Metrics
      description: Enable to collect process metrics. Compatible with Linux and Windows. The collector must be running as root (Linux) and Administrator (Windows).
      type: bool
      default: true

    - name: process_metrics_filtering
      type: enums
      options:
        trackUnchecked: true
      validValues:
        - process.cpu.time
        - process.disk.io
        - process.memory.physical_usage
        - process.memory.virtual_usage
      default: []
      relevantIf:
        - name: enable_process
          operator: equals
          value: true
      advancedConfig: true

    - name: enable_process_filter
      label: Process Name Filtering
      description: Enable to configure filtering for process metrics.
      type: bool
      default: false
      relevantIf:
        - name: enable_process
          operator: equals
          value: true

    - name: process_include
      label: Process Include Filter
      description: List of processes to include for metric collection. Defaults to all processes.
      type: strings
      default: []
      relevantIf:
        - name: enable_process_filter
          operator: equals
          value: true

    - name: process_exclude
      label: Process Exclude Filter
      description: List of processes to exclude from metric collection.
      type: strings
      default: []
      relevantIf:
        - name: enable_process_filter
          operator: equals
          value: true

    - name: process_filter_match_strategy
      label: Process Filter Match Type
      description: Strategy for matching process names.
      type: enum
      default: regexp
      validValues:
        - regexp
        - strict
      relevantIf:
        - name: enable_process_filter
          operator: equals
          value: true

  metrics:
    receivers: |
      - hostmetrics:
          collection_interval: {{ .collection_interval }}s
          scrapers:
            {{ if .enable_load }}
            load:
              {{ if .load_metric_filtering }}
              metrics:
                {{ range $m := .load_metric_filtering }}
                {{ $m }}:
                  enabled: false
                {{ end }}
              {{ end }}
            {{ end }}

            {{ if .enable_filesystem }}
            filesystem:
              {{ if .filesystem_metric_filtering }}
              metrics:
                {{ range $m := .filesystem_metric_filtering }}
                {{ $m }}:
                  enabled: false
                {{ end }}
              {{ end }}
            {{ end }}

            {{ if .enable_memory }}
            memory:
              {{ if .memory_metrics_filtering }}
              metrics:
                {{ range $m := .memory_metrics_filtering }}
                {{ $m }}:
                  enabled: false
                {{ end }}
              {{ end }}
            {{ end }}

            {{ if .enable_network }}
            network:
              {{ if .network_metrics_filtering }}
              metrics:
                {{ range $m := .network_metrics_filtering }}
                {{ $m }}:
                  enabled: false
                {{ end }}
              {{ end }}
            {{ end }}

            {{ if .enable_paging }}
            paging:
              {{ if .paging_metrics_filtering }}
              metrics:
                {{ range $m := .paging_metrics_filtering }}
                {{ $m }}:
                  enabled: false
                {{ end }}
              {{ end }}
            {{ end }}

            {{ if .enable_disk }}
            disk:
              {{ if .disk_metrics_filtering }}
              metrics:
                {{ range $m := .disk_metrics_filtering }}
                {{ $m }}:
                  enabled: false
                {{ end }}
              {{ end }}
            {{ end }}

            {{ if .enable_cpu }}
            cpu:
              {{ if .cpu_metrics_filtering }}
              metrics:
                {{ range $m := .cpu_metrics_filtering }}
                {{ $m }}:
                  enabled: false
                {{ end }}
              {{ end }}
            {{ end }}

            {{ if .enable_processes }}
            processes:
              {{ if .processes_metrics_filtering }}
              metrics:
                {{ range $m := .processes_metrics_filtering }}
                {{ $m }}:
                  enabled: false
                {{ end }}
              {{ end }}
            {{ end }}

            {{ if .enable_process }}
            process:
              {{ if .process_metrics_filtering }}
              metrics:
                {{ range $m := .process_metrics_filtering }}
                {{ $m }}:
                  enabled: false
                {{ end }}
              {{ end }}

              {{ if .enable_process_filter }}
              include:
                names:
                {{ range $p := .process_include }}
                - '{{ $p }}'
                {{ end }}
                match_type: {{ .process_filter_match_strategy }}
              exclude:
                names:
                {{ range $p := .process_exclude }}
                - '{{ $p }}'
                {{ end }}
                match_type: {{ .process_filter_match_strategy }}
              {{ end }}
              mute_process_name_error: true
            {{ end }}

    processors: |
      - resourcedetection:
          detectors: ["system"]
          system:
            hostname_sources: ["os"]
