apiVersion: bindplane.observiq.com/v1
kind: SourceType
metadata:
  name: iis
  displayName: Microsoft IIS
  icon: /icons/sources/microsoft_iis.svg
  description: Collect metrics and logs from Microsoft IIS.
spec:
  version: 0.0.1
  supported_platforms:
    - windows
  parameters:
    # Metrics

    - name: enable_metrics
      label: Enable Metrics
      description: Enable to send metrics.
      type: bool
      default: true

    - name: collection_interval
      label: Collection Interval
      description: How often (seconds) to scrape for metrics.
      type: int
      default: 60
      relevantIf:
        - name: enable_metrics
          operator: equals
          value: true

    - name: metric_filtering
      label: Metric Filtering
      type: bool
      default: false
      relevantIf:
        - name: enable_metrics
          operator: equals
          value: true
      advancedConfig: true

    - name: disable_metrics
      label: Metrics
      description: Toggle the metrics you wish to collect on and off.
      type: enums
      options:
        trackUnchecked: true
      validValues:
        - iis.connection.active
        - iis.connection.anonymous
        - iis.connection.attempt.count
        - iis.network.blocked
        - iis.network.file.count
        - iis.network.io
        - iis.request.count
        - iis.request.queue.age.max
        - iis.request.queue.count
        - iis.request.rejected
        - iis.thread.active
        - iis.uptime
      default: []
      relevantIf:
        - name: enable_metrics
          operator: equals
          value: true
        - name: metric_filtering
          operator: equals
          value: true
      advancedConfig: true

    # Logs

    - name: enable_logs
      label: Enable Logs
      description: Enable to send logs.
      type: bool
      default: true

    - name: file_path
      label: File Path(s)
      description: File or directory paths to tail for logs.
      type: strings
      default: ["C:/inetpub/logs/LogFiles/W3SVC*/**/*.log"]
      relevantIf:
        - name: enable_logs
          operator: equals
          value: true

    - name: exclude_file_log_path
      label: Exclude File Path(s)
      description: File or directory paths to exclude.
      type: strings
      default: []
      relevantIf:
        - name: enable_logs
          operator: equals
          value: true

    - name: timezone
      label: Timezone
      description: RFC3164 only. The timezone to use when parsing timestamps.
      type: timezone
      default: "UTC"
      advancedConfig: true
      relevantIf:
        - name: enable_logs
          operator: equals
          value: true

    - name: start_at
      label: Start At
      description: Start reading file from 'beginning' or 'end'.
      type: enum
      validValues:
        - beginning
        - end
      default: end
      advancedConfig: true
      relevantIf:
        - name: enable_logs
          operator: equals
          value: true

  metrics:
    receivers: |
      {{ if .enable_metrics }}
      - iis:
          collection_interval: {{ .collection_interval }}s

          {{ if .metric_filtering }}
          metrics:
            {{ range $m := .disable_metrics }}
            {{ $m }}:
              enabled: false
            {{ end }}
          {{ end }}
      {{ end }}

    processors: |
      {{ if .enable_metrics }}
      - resourcedetection:
          detectors: ["system"]
          system:
            hostname_sources: ["os"]
      {{ end }}

  logs:
    receivers: |
      {{ if .enable_logs }}
      - plugin:
          path: $OIQ_OTEL_COLLECTOR_HOME/plugins/iis_logs.yaml
          parameters:
            file_path:
              {{ range $fp := .file_path }}
              - '{{ $fp }}'
              {{ end }}
            {{ if .exclude_file_log_path }}
            exclude_file_log_path:
              {{ range $fp := .exclude_file_log_path }}
              - '{{ $fp }}'
              {{ end }}
            {{ end }}
            timezone: {{ .timezone }}
            start_at: {{ .start_at }}
      {{ end }}

    processors: |
      {{ if .enable_logs }}
      - resourcedetection:
          detectors: ["system"]
          system:
            hostname_sources: ["os"]
      {{ end }}
