apiVersion: bindplane.observiq.com/v1
kind: SourceType
metadata:
  name: syslog
  displayName: Syslog
  icon: /icons/sources/network.svg
  description: Receive Syslog from network devices.
spec:
  version: 0.0.1
  supported_platforms:
    - macos
    - linux
    - windows
  parameters:
    - name: protocol
      label: Protocol
      description: The RFC protocol to use when parsing incoming syslog.
      type: enum
      default: "rfc3164"
      validValues:
        - rfc3164
        - rfc5424
      required: true

    - name: connection_type
      label: Transport Protocol
      description: The transport protocol to use.
      type: enum
      default: udp
      validValues:
        - udp
        - tcp

    - name: data_flow
      label: Data Flow
      description: Enable high flow or reduced low flow.
      type: enum
      default: high
      validValues:
        - high
        - low

    - name: listen_port
      label: Listening Port
      description: The port to bind to and receive syslog. Collector must be running as root (Linux) or Administrator (windows) when binding to a port below 1024.
      type: int
      default: 5140
      required: true

    - name: listen_ip
      label: Listening IP Address
      description: The IP address to bind to and receive syslog.
      type: string
      default: "0.0.0.0"
      advancedConfig: true

    - name: timezone
      label: Timezone
      description: RFC3164 only. The timezone to use when parsing timestamps.
      type: timezone
      default: "UTC"
      advancedConfig: true

    - name: enable_tls
      label: Enable TLS
      description: Whether or not to use TLS.
      type: bool
      default: false
      relevantIf:
        - name: connection_type
          operator: equals
          value: "tcp"
      advancedConfig: true

    - name: cert_file
      label: TLS Certificate File
      description: Path to the x509 PEM certificate.
      type: string
      required: false
      default: ""
      relevantIf:
        - name: enable_tls
          operator: equals
          value: true
      advancedConfig: true

    - name: key_file
      label: TLS Private Key File
      description: Path to the x509 PEM private key.
      type: string
      required: false
      default: ""
      relevantIf:
        - name: enable_tls
          operator: equals
          value: true
      advancedConfig: true

    - name: ca_file
      label: TLS Certificate Authority File
      description: When set, enforces mutual TLS authentication and verifies client certificates.
      type: string
      required: false
      default: ""
      relevantIf:
        - name: enable_tls
          operator: equals
          value: true
      advancedConfig: true

    - name: tls_min_version
      label: Minimum TLS Version
      description: The minimum TLS version to support. 1.0 and 1.1 should not be considered secure.
      type: enum
      default: "1.2"
      validValues:
        - "1.3"
        - "1.2"
        - "1.1"
        - "1.0"
      relevantIf:
        - name: enable_tls
          operator: equals
          value: true
      advancedConfig: true

  logs:
    receivers: |
      - plugin/syslog:
          path: $OIQ_OTEL_COLLECTOR_HOME/plugins/syslog_logs.yaml
          parameters:
            connection_type: {{ .connection_type }}
            protocol: {{ .protocol }}
            listen_address: {{ .listen_ip }}:{{ .listen_port }}
            # Used for RFC3164 Only
            timezone: {{ .timezone }}
            tls_certificate_path: "{{ .cert_file }}"
            tls_private_key_path: "{{ .key_file }}"
            tls_ca_path: "{{ .ca_file }}"
            tls_min_version: "{{ .tls_min_version }}"
            data_flow: {{ .data_flow }}

    processors: |
      - resourcedetection:
          detectors: ["system"]
          system:
            hostname_sources: ["os"]
