apiVersion: bindplane.observiq.com/v1
kind: Configuration
metadata:
  name: macos
  labels:
    platform: macos
    app: cabin
spec:
  contentType: text/yaml
  sources:
    # name is optional and this will become MacOS_1 if none is specified or MacOS_name if a name is specified
    - type: MacOS
      parameters:
        # using default parameter values for anything missing
        - name: enable_system_log
          value: false
    - type: MacOS
      parameters:
        # using default parameter values for anything missing
        - name: enable_system_log
          value: true
  destinations:
    # name indicates an existing resource with the specified name, destinations could also be inline without a name
    - name: cabin-production-logs
  raw: >
    receivers:
      otlp:
        protocols:
          grpc:
          http:
      otlp/2:
        protocols:
          grpc:
            endpoint: 0.0.0.0:55690

    processors:
      batch:
      batch/test:

    exporters:
      otlp:
        endpoint: otelcol:4317
      otlp/2:
        endpoint: otelcol2:4317

    extensions:
      health_check:
      pprof:
      zpages:

    service:
      extensions: [health_check,pprof,zpages]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]
        traces/2:
          receivers: [otlp/2]
          processors: [batch/test]
          exporters: [otlp/2]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]
  selector:
    matchLabels:
      "configuration": macos
