# bindplane configuration create --name "cabin production configuration" -f config.yaml --labels app=cabin,env=production --description ""
# bindplane configuration get --name "cabin production configuration" --output otel
apiVersion: bindplane.observiq.com/v1beta
kind: Configuration
metadata:
  name: raw-malformed
  labels:
    app: cabin
    env: production
spec:
  contentType: text/yaml
  raw: >
    receivers:
      otlp:
        protocols:
          grpc:
          http:
      otlp/2:
        protocols:
          grpc:
            endpoint: 0.0.0.0:55690

    processors:
      batch:
      batch/test:

    exporters:
      otlp:
        endpoint: otelcol:4317
      otlp/2:
        endpoint: otelcol2:4317

    extensions:
      health_check:
      pprof:
      zpages:

    service:
      extensions: [health_check,pprof,zpages]
      pipelines:
        traces:
          receivers: [otlp][][]
          processors: [batch]
          exporters: [otlp]
        traces/2:
          receivers: [otlp/2]
          processors: [batch/test]
          exporters: [otlp/2]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]
  # agents with labels "app=cabin" and "env=production" will use this exporter
  selector:
    matchLabels:
      app: cabin
      env: production
      # platform: kubernetes
      # cluster: cabin-production
