apiVersion: bindplane.observiq.com/v1beta
kind: Source
metadata:
  name: bar
  description: bar is my old macbook with a touchbar
spec:
  type: MacOS
  parameters:
    - name: enable_system_log
      value: true
    - name: install_log_path
      value:
        - array
        - but
        - not
        - supposed
        - to
        - be
    - name: start_at
      value: middle
    - name: unknown
      value: doesn't matter
