apiVersion: bindplane.observiq.com/v1beta
kind: Source
metadata:
  name: bar
  description: bar is my old macbook with a touchbar
  labels:
    "bad label name": macos
spec:
  type: MacOS
  parameters:
    - name: enable_system_log
      value: true
