apiVersion: bindplane.observiq.com/v1beta
kind: ProcessorType
metadata:
  name: custom
  displayName: Custom
spec:
  version: 0.0.1
  parameters:
    - name: configuration
      label: Configuration
      description: Enter any OpenTelemetry Processor and the YAML will be inserted into the configuration. Processor configuration documentation can be found here https://github.com/observIQ/observiq-otel-collector/blob/main/docs/processors.md.
      type: yaml
      required: true

  logs+metrics+traces:
    processors: |
      - {{ .configuration | nindent 2 }}
