apiVersion: bindplane.observiq.com/v1beta
kind: ProcessorType
metadata:
  name: custom
  displayName: Custom
  description: Insert a custom OpenTelemetry processor configuration.
spec:
  version: 0.0.1
  parameters:
    - name: configuration
      label: Configuration
      description: Enter any OpenTelemetry Processor and the YAML will be inserted into the configuration. Processor configuration documentation can be found here https://github.com/observIQ/observiq-otel-collector/blob/main/docs/processors.md.
      type: yaml
      required: true

    - name: telemetry_types
      label: Enable Telemetry
      type: enums
      description: "Select which types of telemetry the processor should support."
      validValues: ["Metrics", "Logs", "Traces"]
      default: ["Metrics", "Logs", "Traces"]

  logs:
    processors: |
      {{ if has "Logs" .telemetry_types }}
      - {{ .configuration | nindent 2 }}
      {{ end }}

  metrics:
    processors: |
      {{ if has "Metrics" .telemetry_types }}
      - {{ .configuration | nindent 2 }}
      {{ end }}


  traces:
    processors: |
      {{ if has "Traces" .telemetry_types }}
      - {{ .configuration | nindent 2 }}
      {{ end }}
