apiVersion: bindplane.observiq.com/v1
kind: ProcessorType
metadata:
  name: delete_resource
  displayName: Delete Resource Attribute
  description: Delete resource attributes from metrics, traces, and logs.
spec:
  version: 0.0.1
  parameters:
    - name: resources
      label: Resource Keys
      type: strings
      required: true

    - name: telemetry_types
      label: Enable Telemetry
      type: enums
      description: "Select which types of telemetry you'd like to enable this processor for."
      validValues: ["Metrics", "Logs", "Traces"]
      default: ["Metrics", "Logs", "Traces"]

  metrics:
    processors: |
      {{ if has "Metrics" .telemetry_types }}
      - resource:
          attributes:
            {{ range $k := .resources }}
            - key: '{{ $k }}'
              action: delete
            {{ end }}
      {{ end }}
  logs:
    processors: |
      {{ if has "Logs" .telemetry_types }}
      - resource:
          attributes:
            {{ range $k := .resources }}
            - key: '{{ $k }}'
              action: delete
            {{ end }}
      {{ end }}
  traces:
    processors: |
      {{ if has "Traces" .telemetry_types }}
      - resource:
          attributes:
            {{ range $k := .resources }}
            - key: '{{ $k }}'
              action: delete
            {{ end }}
      {{ end }}
