apiVersion: bindplane.observiq.com/v1
kind: ProcessorType
metadata:
  name: delete_attribute
  displayName: Delete Log Record Attribute
  description: Delete a log record attribute.
spec:
  version: 0.0.1
  parameters:
    - name: attributes
      label: Attribute Keys
      type: strings
      required: true

  logs:
    processors: |
      - attributes:
          actions:
            {{ range $k := .attributes }}
            - key: '{{ $k }}'
              action: delete
            {{ end }}
